### ISSUE TITLE
creationTimestamp is null in all receipts

### ISSUE THREAD

**Issue by corneliusweig** [kubernetes-sigs/krew#632]
All my receipts have such a header:

```yaml
metadata:
   creationTimestamp: null
   name: krew
```

including `creationTimestamp`. This field carries no information and is annoying. There are two options:

* Get rid of this obsolete field.
* Fill the field when installing the plugin.

Following https://kubernetes.io/docs/reference/using-api/api-concepts/#generated-values, it seems most inline with k8s concepts, if the stored timestamp is the time when the plugin was first installed.

/help
