### ISSUE TITLE
Upgrade from 0.4.1 => -.4.3 on macOS not working

### ISSUE THREAD

**Issue by chipzoller** [kubernetes-sigs/krew#758]
Running `krew upgrade` does not seem to have any effect on macOS 10.14 with version 0.4.1.

`krew.yaml`
```yaml
$ cat ~/.krew/receipts/krew.yaml
apiVersion: krew.googlecontainertools.github.com/v1alpha2
kind: Plugin
metadata:
  creationTimestamp: "2022-02-27T01:36:02Z"
  name: krew
spec:
  caveats: |
    krew is now installed! To start using kubectl plugins, you need to add
    krew's installation directory to your PATH:

      * macOS/Linux:
        - Add the following to your ~/.bashrc or ~/.zshrc:
            export PATH="${KREW_ROOT:-$HOME/.krew}/bin:$PATH"
        - Restart your shell.

      * Windows: Add %USERPROFILE%\.krew\bin to your PATH environment variable

    To list krew commands and to get help, run:
      $ kubectl krew
    For a full list of available plugins, run:
      $ kubectl krew search

    You can find documentation at
      https://krew.sigs.k8s.io/docs/user-guide/quickstart/.
  homepage: https://krew.sigs.k8s.io/
  platforms:
  - bin: krew
    files:
    - from: ./krew-darwin_amd64
      to: krew
    - from: ./LICENSE
      to: .
    selector:
      matchLabels:
        arch: amd64
        os: darwin
    sha256: 6f6a774f03ad4190a709d7d4dcbb4af956ca0eb308cb0d0a44abc90777b0b21a
    uri: https://github.com/kubernetes-sigs/krew/releases/download/v0.4.3/krew-darwin_amd64.tar.gz
  - bin: krew
    files:
    - from: ./krew-darwin_arm64
      to: krew
    - from: ./LICENSE
      to: .
    selector:
      matchLabels:
        arch: arm64
        os: darwin
    sha256: 22f29ce3c3c9c030e2eaf3939d2b00f0187dfdbbfaee37fba8ffaadc46e51372
    uri: https://github.com/kubernetes-sigs/krew/releases/download/v0.4.3/krew-darwin_arm64.tar.gz
  - bin: krew
    files:
    - from: ./krew-linux_amd64
      to: krew
    - from: ./LICENSE
      to: .
    selector:
      matchLabels:
        arch: amd64
        os: linux
    sha256: 5df32eaa0e888a2566439c4ccb2ef3a3e6e89522f2f2126030171e2585585e4f
    uri: https://github.com/kubernetes-sigs/krew/releases/download/v0.4.3/krew-linux_amd64.tar.gz
  - bin: krew
    files:
    - from: ./krew-linux_arm
      to: krew
    - from: ./LICENSE
      to: .
    selector:
      matchLabels:
        arch: arm
        os: linux
    sha256: 68eb9e9f5bba29c7c19fb52bfc43a31300f92282a4e81f0c51ad26ed2c73eb03
    uri: https://github.com/kubernetes-sigs/krew/releases/download/v0.4.3/krew-linux_arm.tar.gz
  - bin: krew
    files:
    - from: ./krew-linux_arm64
      to: krew
    - from: ./LICENSE
      to: .
    selector:
      matchLabels:
        arch: arm64
        os: linux
    sha256: 0994923848882ad0d4825d5af1dc227687a10a02688f785709b03549dd34d71d
    uri: https://github.com/kubernetes-sigs/krew/releases/download/v0.4.3/krew-linux_arm64.tar.gz
  - bin: krew.exe
    files:
    - from: ./krew-windows_amd64.exe
      to: krew.exe
    - from: ./LICENSE
      to: .
    selector:
      matchLabels:
        arch: amd64
        os: windows
    sha256: d1343a366a867e9de60b23cc3d8ee935ee185af25ff8f717a5e696ba3cae7c85
    uri: https://github.com/kubernetes-sigs/krew/releases/download/v0.4.3/krew-windows_amd64.tar.gz
  shortDescription: Package manager for kubectl plugins.
  version: v0.4.3
status:
  source:
    name: default
```

```sh
$ k krew upgrade
Updated the local copy of plugin index.
Upgrading plugin: cert-manager
Skipping plugin cert-manager, it is already on the newest version
Upgrading plugin: ctx
Skipping plugin ctx, it is already on the newest version
Upgrading plugin: example
Skipping plugin example, it is already on the newest version
Upgrading plugin: get-all
Skipping plugin get-all, it is already on the newest version
Upgrading plugin: krew
Skipping plugin krew, it is already on the newest version
Upgrading plugin: kyverno
Skipping plugin kyverno, it is already on the newest version
Upgrading plugin: neat
Skipping plugin neat, it is already on the newest version
Upgrading plugin: ns
Skipping plugin ns, it is already on the newest version
Upgrading plugin: starboard
Skipping plugin starboard, it is already on the newest version
Upgrading plugin: view-webhook
Skipping plugin view-webhook, it is already on the newest version
A newer version of krew is available (v0.4.1 -> v0.4.3).
Run "kubectl krew upgrade" to get the newest version!
```

```sh
$ k krew version
OPTION            VALUE
GitTag            v0.4.1
GitCommit         ffa2933f
IndexURI          https://github.com/kubernetes-sigs/krew-index.git
BasePath          /Users/chipzoller/.krew
IndexPath         /Users/chipzoller/.krew/index/default
InstallPath       /Users/chipzoller/.krew/store
BinPath           /Users/chipzoller/.krew/bin
DetectedPlatform  darwin/amd64
```

I also see this snippet in more verbose output:

```log
I0226 21:07:11.910837   15364 scanner.go:78] Reading plugin "krew" from /Users/chipzoller/.krew/index/default/plugins
Upgrading plugin: krew
I0226 21:07:11.911618   15364 platform.go:43] Matching platform for labels(arch=amd64,os=darwin)
I0226 21:07:11.911632   15364 platform.go:51] Found matching platform with index (0)
I0226 21:07:11.911638   15364 upgrade.go:59] Comparing versions: current=v0.4.3 target=v0.4.3
I0226 21:07:11.911645   15364 upgrade.go:63] Plugin does not need upgrade (v0.4.3 ≥ v0.4.3)
Skipping plugin krew, it is already on the newest version
```

Slack conversation: https://kubernetes.slack.com/archives/CTJNMDM24/p1645926504899139

cc @chriskim06
