### ISSUE TITLE
Proposal: Supporting more artifact retreval methods

### ISSUE THREAD

**Issue by endzyme** [kubernetes-sigs/krew#817]
Related to #684 and #816 

## Overview

I am looking for some initial implementation feedback on supporting private GitHub repository releases as well as a few other potential artifact repositories.

The intent here is to support _some_ way of running custom commands, which return an artifact file via stdout. This could solve #684 by running something like `gh api -H Accept:application/octet-stream /repos/kubernetes-sigs/krew/releases/assets/55894121` to download artifacts from a private GitHub repo's release assets. It could also allow people to have their on private krew indexes which rely upon local machine tooling to get the artifacts. I'm thinking example commands like `aws s3 cp s3://my-fancy-private-bucket/my-cool-krew-plugin.tgz -`. This type of support could separate the concerns of auth to the local machine running the installation.

I initially wanted to implement this as an S3 SDK scheme but decided it would be better to enable more options via running commands on the local machine. Happy to discuss alternative approaches here too.

### Early feedback request on the design

Keep in mind my testing and work is pretty rough and just an initial concept.

1. Should this implementation bloat the `uri` spec key to support other "schemes" (such as `file://` and `cmd://`) or should it really be a separate key in the plugin manifest spec? (Providing string like `cmd://run-my-super-sweet-script -i thing -o otherthing` just feels kinda not ideal.)

2. Should this leverage temp files on the file system to "buffer" the stdout from the "artifact download command"? I initially attempted to use `exec.Command()` and `exec.Command().Stdout()` but hit issues with the pipe closing before the stream could be read (appears to be how `exec.Command()` is intended to function).

3. Is this introducing too much of a security risk, allowing manifests to effectively execute arbitrary code via krew when installing plugins?

Below is an example plugin manifest using this PR to give an example of how this is written right now.

```yaml
apiVersion: krew.googlecontainertools.github.com/v1alpha2
kind: Plugin
metadata:
  name: testfile
spec:
  version: "v0.0.1"
  homepage: https://somedomain.com/
  shortDescription: Throwin testfiles
  caveats: |
    Something something testfile

  platforms:
  - uri: cmd://gh api -H Accept:application/octet-stream /repos/kubernetes-sigs/krew/releases/assets/55894121
    sha256: 5df32eaa0e888a2566439c4ccb2ef3a3e6e89522f2f2126030171e2585585e4f
    bin: testfile
    files:
    - from: ./krew-linux_amd64
      to: testfile
    selector:
      matchExpressions:
      - key: "os"
        operator: "In"
        values:
        - linux
        - darwin
```

**Comment by endzyme** [comment]
@ahmetb Sorry for the rather lazy approach of starting the discussion by pasting the PR initial comment. If you'd like a different method of starting the design discussion, let me know what you expect and I can write up a proposal.

**Comment by endzyme** [comment]
@ahmetb Anything I can help with to get the ball rolling here on what you need to have a design discussion? Happy to connect in the Kubernetes Slack too. :smile: Happy Holidays and hope you have a great New Year

**Comment by chriskim06** [comment]
i think points 1 and 3 you made are definitely important. i dont like the idea of executing an arbitrary command to get the release assets because its a security risk like you said. 

i think homebrew has specific release strategies for downloading assets from non-public github urls (private github repo, s3, etc). maybe something like that could work here as well. speaking about private github specifically, i think if we kept the uri as a url to a private release asset then you have to add a `Authorization: token ...` header to the request, which presents another challenge of how krew should get that token. a predefined env var would be possible but that adds extra required knowledge on the users.

**Comment by esatterwhite** [comment]
Most package managers I've encountered that handle this have allowed me to specify a url to the source. In the case of a git repo, it is just the git repo, and a ref. 

```lua
source = {
  url = 'git+https://github.com/<owner>/<repo>.git',
  tag = 'v2.2.1',
}
```

where the protocol of the url tells the manager how it is supposed to get the asset.

```txl
github+https://github.com/<owner>/<repo>.git
```

tells you the asset lives on a github release for example, which means the repo could be private and needs some additional information. Most github things have standardized around having a `GITHUB_TOKEN` environment variable set on the machine running the command to handle authenticated requests.

**Comment by endzyme** [comment]
@esatterwhite, do you have any examples you can link here. I'm happy to keep driving this forward a little, but I want to see if the examples have use cases for other schemes or protocols like s3/gcs or others. Thanks!

**Comment by chriskim06** [comment]
dug around homebrew a bit and they are also using the github api https://github.com/Homebrew/brew/blob/master/Library/Homebrew/utils/github/api.rb#L196-L198 with the token defined in an env var i think. im not exactly sure how a formula defines that the artifact to install is in a private repo though (and homebrew also allows people to define how something is installed instead of just providing a binary to download). 

i think if we are going to support this we'll need to use the api as well and come up with a good design around some of the comments i made earlier

**Comment by esatterwhite** [comment]
@endzyme https://github.com/luarocks/luarocks/tree/master/src/luarocks/fetch

**Comment by chriskim06** [comment]
@esatterwhite that looks like stuff to download a private repo (which i believe works with the custom indexes feature in krew). the problem we have right now is if a plugin manifest defines a binary from a release in a private repo. i havent figured out a way to download an asset using the `https://github.com/{owner}/{repo}/releases/download/{tag}/{artifact}` url. i think we need the github api in order to do that which would require some changes to the plugin schema i think and that requires some design

**Comment by chriskim06** [comment]
i think the main points of concern are
- making sure that existing manifests dont need to be updated
- doing this in a way that is extensible to other potential artifact sources
- how to handle authentication credentials

with that being said here are some very preliminary thoughts i had:

we could add a new `Release` type that implements the `download.Fetcher` interface and include this in the `Plugin` type. `Release` would need to implement the `UnmarshalJSON` method and use `json.RawMessage` to allow unmarshaling to different types (in case we support other download options like s3 in the future). a release would look like
```
platforms:
- selector:
    ...
  release:
    type: github
    metadata:
      baseURL: ...
      repo: ...
      release: ...
      asset: ...
  ...
```
the implementation of these different ways to download releases would just need to implement `Get(string) (io.ReadCloser, error)`, could have different schemas themselves, and would need to update the `Release` type's implementation of `UnmarshalJSON`. 

the rough idea above doesnt address how the github token is picked up by krew. that is probably one of the more difficult points to address with all this. we've talked about potentially having a config file in the past but we havent really needed one afaik. an env var is much simpler from a dev perspective but adds a bit of extra required knowledge on the user's part (although i dont think much and is a common paradigm with other tools). 

@ahmetb curious to hear your take on all this.
