### ISSUE TITLE
Proposal: Download Binary File and Download License via URI

### ISSUE THREAD

**Issue by joshbrgs** [kubernetes-sigs/krew#835]
I believe it would be a great feature to accept standalone binaries as well as Archives. This could open the possibility for more projects to index their plugins with krew without needing to change their GH workflows if they are not releasing Archives. One could modify the yaml to have a license field where the URI to the License would be located. As an example with the argo rollouts project: 

```
  - uri: https://github.com/argoproj/argo-rollouts/releases/download/v1.5.1/kubectl-argo-rollouts-windows-amd64
    sha256: 4c71b696d5821b4740c0d16e55e8793146c9dc0675d1be869f73934e9f847431
    bin: kubectl-argo-rollouts
    license: https://raw.githubusercontent.com/argoproj/argo-rollouts/v1.5.1/LICENSE
    selector:
      matchLabels:
        os: windows
        arch: amd64
```

I would be willing to contribute this. 👍🏼 

/kind proposal
